In [1]:
from cv2 import cv2 
import numpy as np 
 
left_ear_cascade = cv2.CascadeClassifier('haarcascade_mcs_leftear.xml') 
right_ear_cascade = cv2.CascadeClassifier('haarcascade_mcs_rightear.xml') 
 
if left_ear_cascade.empty(): 
  raise IOError('Unable to load the left ear cascade classifier xml file') 
 
if right_ear_cascade.empty(): 
  raise IOError('Unable to load the right ear cascade classifier xml file') 
 
#cap = cv2.VideoCapture(0)
#scaling_factor = 0.5
image = cv2.imread('er1.jpg') 
print(image.shape)
#factor = 0.1492
dim = (int(image.shape[1]*0.3),int(image.shape[0]*0.3))
img2gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# add a threshold
ret, mask = cv2.threshold(img2gray, 220, 255, cv2.THRESH_BINARY_INV)
#cv2.imshow('Ear Detector', ear_img) 
mask_inv = cv2.bitwise_not(mask)
resized = cv2.resize(image,dim, interpolation = cv2.INTER_AREA)
mask = cv2.resize(mask, (resized.shape[1],resized.shape[0]), interpolation = cv2.INTER_AREA)
mask_inv = cv2.resize(mask_inv, (resized.shape[1],resized.shape[0]), interpolation = cv2.INTER_AREA)

#print(frame.shape)
#dim = (int(image.shape[1]*0.20),int(image.shape[0]*0.20))
while True:
    #ret, frame = cap.read() 
    frame = cv2.imread('index4.jpg')
    #frame = cv2.resize(frame, None, fx=scaling_factor, fy=scaling_factor, interpolation=cv2.INTER_AREA)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)  
    left_ear = left_ear_cascade.detectMultiScale(gray, scaleFactor=1.3, minNeighbors=3) 
    right_ear = right_ear_cascade.detectMultiScale(gray, scaleFactor=1.3, minNeighbors=3) 
    print(frame.shape)
    for (x,y,w,h) in left_ear: 
        
        cv2.rectangle(frame, (x,y), (x+w,y+h), (0,255,0), 3)
        #cv2.circle(frame,(int(x+w*0.7),int(y+h*0.8)),5,(255,255,255),-1,8,0)
        print(resized.shape)
        x1 = int(x+w*0.7)
        x2 = x1 + dim[1]
        y1 = int(y+h*0.8)
        y2 = y1 + dim[0]
        print(x2-x1,y2-y1)
        print(x,y,x+w,y+h)
        print(w,h)
        roi = frame[int(y+h*0.8):int(y+h*0.8)+dim[1],int(x+w*0.7)-(int(dim[0]/2)):int(x+w*0.7)+(int(dim[0]/2))]
        print(roi.shape)
        roi_bg = cv2.bitwise_and(roi,roi,mask = mask_inv)
        # roi_fg contains the orignal location of earring
        roi_fg = cv2.bitwise_and(resized,resized,mask = mask)
        # joining the roi_bg and roi_fg
        dst = cv2.add(roi_bg,roi_fg)
        cv2.imshow('Ear Detector', dst) 
        cv2.waitKey(10)
        frame[int(y+h*0.8):int(y+h*0.8)+dim[1],int(x+w*0.7)-(int(dim[0]/2)):int(x+w*0.7)+(int(dim[0]/2))]=dst
        
    for (x,y,w,h) in right_ear: 
        cv2.rectangqle(frame, (x,y), (x+w,y+h), (255,0,0), 3) 

    cv2.imshow('Ear Detector', frame)
    #cv2.imshow('Ear Detector', dst)
    
    #c = cv2.waitKey(1) 
    if cv2.waitKey(3000) & 0xFF == ord('q'):
        break

#cap.release() 
cv2.destroyAllWindows()

(201, 109, 3)
(225, 225, 3)
(60, 32, 3)
60 32
95 66 125 116
30 50
(60, 32, 3)
(225, 225, 3)
(60, 32, 3)
60 32
95 66 125 116
30 50
(60, 32, 3)


In [5]:
def auto_map_images(img_dim,tar_dim,det_dim):
    mul_factor = (det_dim[2]-det_dim[0])/tar_dim[1]
    print(mul_factor)
    new_tar_dim = tuple([int(mul_factor*x)for x in tar_dim])
    print(new_tar_dim)
    left_space = img_dim[1]-det_dim[3]
    print(left_space)
    if left_space>new_tar_dim[0]:
        factor = mul_factor
    else:
        factor = left_space/tar_dim[0]
    return factor   

In [6]:
im = (95,66,125,116)
im1 = tuple([2*x for x in im])
im1
factor = auto_map_images((225, 225),(201, 109),(95,66,125,116))
factor


0.27522935779816515
(55, 30)
109


0.27522935779816515

In [ ]:
import cv2
import numpy as np
img = cv2.imread('input.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray, 1.3, 5)
for(x,y,w,h) infaces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for(ex,ey,ew,eh) in eyes
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
        cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
import cv2
import numpy as np

#left_ear_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
#left_ear_cascade = cv2.CascadeClassifier('haarcascade_upperbody.xml')
left_ear_cascade = cv2.CascadeClassifier('haarcascade_mcs_upperbody.xml')

if left_ear_cascade.empty():
  raise IOError('Unable to load the left ear cascade classifier xml file')
img = cv2.imread('image.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
left_ear = left_ear_cascade.detectMultiScale(gray, 1.3, 5)
print(len(left_ear))
for (x,y,w,h) in left_ear:
    cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,0), 3)

cv2.imshow('Ear Detector', img)
cv2.waitKey()
cv2.destroyAllWindows()

1


In [2]:
from cv2 import cv2 
import numpy as np 
 
left_ear_cascade = cv2.CascadeClassifier('haarcascade_mcs_leftear.xml') 
right_ear_cascade = cv2.CascadeClassifier('haarcascade_mcs_rightear.xml') 
 
if left_ear_cascade.empty(): 
  raise IOError('Unable to load the left ear cascade classifier xml file') 
 
if right_ear_cascade.empty(): 
  raise IOError('Unable to load the right ear cascade classifier xml file') 
scaling_factor = 0.5
ear_img = cv2.imread('earring1.jpg', 1)
ear_img = cv2.resize(frame, None, fx=scaling_factor, fy=scaling_factor, interpolation=cv2.INTER_AREA)
org_height, org_width, channel = ear_img.shape

img2gray = cv2.cvtColor(ear_img, cv2.COLOR_BGR2GRAY)

# add a threshold
ret, mask = cv2.threshold(img2gray, 220, 255, cv2.THRESH_BINARY_INV)
#cv2.imshow('Ear Detector', ear_img) 
mask_inv = cv2.bitwise_not(mask)
#cv2.waitKey(10000) 
#cv2.imshow('Ear Detector', ear_img)  
#cap = cv2.VideoCapture(0)
#scaling_factor = 0.5
while True:
    #ret, frame = cap.read() 
    frame = cv2.imread('index1.jpg')
    #frame = cv2.resize(frame, None, fx=scaling_factor, fy=scaling_factor, interpolation=cv2.INTER_AREA)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)  
    left_ear = left_ear_cascade.detectMultiScale(gray, scaleFactor=1.3, minNeighbors=3) 
    right_ear = right_ear_cascade.detectMultiScale(gray, scaleFactor=1.3, minNeighbors=3) 
    print(left_ear)
    for (x,y,w,h) in left_ear: 
        earring_height = h
        earring_width = earring_height * org_width / org_height

        x1 = int(x - (earring_width/4))
        x2 = int(x + w + (earring_width/4))
        y1 = int(y + h - (earring_height/2))
        y2 = int(y + h + (earring_height/2))

        earring_width = x2 - x1
        earring_height = y2 - y1

        earring = cv2.resize(ear_img, (earring_width,earring_height), interpolation = cv2.INTER_AREA)
        mask = cv2.resize(mask, (earring_width,earring_height), interpolation = cv2.INTER_AREA)
        mask_inv = cv2.resize(mask_inv, (earring_width,earring_height), interpolation = cv2.INTER_AREA)

        roi = frame[y1:y2, x1:x2]

        roi_bg = cv2.bitwise_and(roi,roi,mask = mask_inv)
 
        # roi_fg contains the orignal location of earring
        roi_fg = cv2.bitwise_and(earring,earring,mask = mask)
     
        # joining the roi_bg and roi_fg
        dst = cv2.add(roi_bg,roi_fg)
 
        # placing the joined image and saving to dst back over the original image
        frame[y1:y2, x1:x2] = dst 

    for (x,y,w,h) in right_ear: 
        cv2.rectangle(frame, (x,y), (x+w,y+h), (255,0,0), 3) 

    cv2.imshow('Ear Detector', frame) 
    #c = cv2.waitKey(1) 
    if cv2.waitKey(3000) & 0xFF == ord('q'):
        break

#cap.release() 
cv2.destroyAllWindows()

[[102  12  98 163]]


error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\core\src\arithm.cpp:245: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'cv::binary_op'


In [3]:
import cv2
import numpy as np
img = cv2.imread('index1.jpg')
img.shape

(183, 275, 3)

In [6]:
import cv2
import numpy as np
imgshirt = cv2.imread('shirt.png',1)
musgray = cv2.cvtColor(imgshirt,cv2.COLOR_BGR2GRAY) #grayscale conversion
ret, orig_mask = cv2.threshold(musgray,150 , 255, cv2.THRESH_BINARY)
orig_mask_inv = cv2.bitwise_not(orig_mask)
origshirtHeight, origshirtWidth = imgshirt.shape[:2]
face_cascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
cap=cv2.VideoCapture(0)
ret,img=cap.read()
img_h, img_w = img.shape[:2]
while True:
    ret,img=cap.read()
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces=face_cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)

        face_w = w
        face_h = h
        face_x1 = x
        face_x2 = face_x1 + face_h
        face_y1 = y
        face_y2 = face_y1 + face_h

        # set the shirt size in relation to tracked face
        shirtWidth = 3 * face_w
        shirtHeight = int(shirtWidth * origshirtHeight / origshirtWidth)


        shirt_x1 = face_x2 - int(face_w/2) - int(shirtWidth/2) #setting shirt centered wrt recognized face
        shirt_x2 = shirt_x1 + shirtWidth
        shirt_y1 = face_y2 + 5 # some padding between face and upper shirt. Depends on the shirt img
        shirt_y2 = shirt_y1 + shirtHeight

        # Check for clipping
        if shirt_x1 < 0:
            shirt_x1 = 0
        if shirt_y1 < 0:
            shirt_y1 = 0
        if shirt_x2 > img_w:
            shirt_x2 = img_w
        if shirt_y2 > img_h:
            shirt_y2 = img_h

        shirtWidth = shirt_x2 - shirt_x1
        shirtHeight = shirt_y2 - shirt_y1
        if shirtWidth < 0 or shirtHeight < 0:
            continue

        # Re-size the original image and the masks to the shirt sizes
        shirt = cv2.resize(imgshirt, (shirtWidth,shirtHeight), interpolation = cv2.INTER_AREA) #resize all,the masks you made,the originla image,everything
        mask = cv2.resize(orig_mask, (shirtWidth,shirtHeight), interpolation = cv2.INTER_AREA)
        mask_inv = cv2.resize(orig_mask_inv, (shirtWidth,shirtHeight), interpolation = cv2.INTER_AREA)

        # take ROI for shirt from background equal to size of shirt image
        roi = img[shirt_y1:shirt_y2, shirt_x1:shirt_x2]


        # roi_bg contains the original image only where the shirt is not
        # in the region that is the size of the shirt.
        roi_bg = cv2.bitwise_and(roi,roi,mask = mask)
        roi_fg = cv2.bitwise_and(shirt,shirt,mask = mask_inv)
        dst = cv2.add(roi_bg,roi_fg)
        img[shirt_y1:shirt_y2, shirt_x1:shirt_x2] = dst


        break
    cv2.imshow('img',img)
    if cv2.waitKey(1) == ord('q'):
        break;
cap.release() # Destroys the cap object
cv2.destroyAllWindows() # Destroys all the windows created by imshow

error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [2]:
import urllib.request
import cv2
import numpy as np
import time
URL = "http://192.168.0.107:8080/shot.jpg"
while True:    
    img_arr = np.array(bytearray(urllib.request.urlopen(URL).read()),dtype=np.uint8)
    print(img_arr)
    img = cv2.imdecode(img_arr,-1)
    cv2.imwrite('web1.jpg',img)
    cv2.imshow('IPWebcam',img)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

[255 216 255 ...  15 255 217]
[255 216 255 ...   0 255 217]
[255 216 255 ...   7 255 217]
[255 216 255 ...  63 255 217]
[255 216 255 ... 127 255 217]
[255 216 255 ... 127 255 217]
[255 216 255 ...  25 255 217]
[255 216 255 ...   0 255 217]
[255 216 255 ...   0 255 217]
[255 216 255 ...  63 255 217]
[255 216 255 ...  63 255 217]
[255 216 255 ...   1 255 217]
[255 216 255 ...  63 255 217]
[255 216 255 ... 127 255 217]
[255 216 255 ...   1 255 217]
[255 216 255 ...   3 255 217]
[255 216 255 ...  63 255 217]
[255 216 255 ...  15 255 217]
[255 216 255 ...  63 255 217]
[255 216 255 ...  63 255 217]
[255 216 255 ... 127 255 217]
[255 216 255 ...  15 255 217]
[255 216 255 ...  71 255 217]
[255 216 255 ... 128 255 217]
[255 216 255 ... 159 255 217]
[255 216 255 ...   0 255 217]
[255 216 255 ...  15 255 217]
[255 216 255 ...   3 255 217]
[255 216 255 ...  63 255 217]
[255 216 255 ...  31 255 217]
[255 216 255 ...   1 255 217]
[255 216 255 ...  31 255 217]
[255 216 255 ...  63 255 217]
[255 216 2